/**
 * @fileoverview UI constants shared across Shiny View editor interactions.
 */

export const DUPLICATE_OFFSET = 24;

export const GENERATE_CLASS_WIDTH = 200;
export const GENERATE_CLASS_HEIGHT = 150;
export const GENERATE_CLASS_MARGIN = 40;

export const PLACEMENT_OVERLAY_DRAG_THRESHOLD = 4;
export const PLACEMENT_OVERLAY_Z_INDEX = 20;

export const RELATIONSHIP_RECONNECT_RADIUS = 12;
export const RELATIONSHIP_EDGE_HIT_PATH_STROKE_WIDTH = 14;
export const RELATIONSHIP_EDGE_DASH_PATTERN = "6 4";
export const RELATIONSHIP_EDGE_TEXT_BOX_WIDTH = 96;
export const RELATIONSHIP_EDGE_TEXT_BOX_HEIGHT = 28;
export const RELATIONSHIP_EDGE_TEXT_BOX_X_OFFSET = 48;
export const RELATIONSHIP_EDGE_TEXT_BOX_Y_OFFSET = 14;
export const RELATIONSHIP_EDGE_MULTIPLICITY_POSITION_FRACTION = 0.3;
