classDiagram
	namespace NewNamespace {
		class ConversationThread {
			+UUID id
			+List~TextMessage~ messages
			+List~UserContact~ participants
			+addMessage(TextMessage message) void
			+addParticipant(UserContact participant) void
		}
		class UserContact {
			+UUID id
			+String name
			+String emailAddress
			+List~CommunicationChannel~ preferredChannels
			+addCommunicationChannel(CommunicationChannel channel) void
			+removeCommunicationChannel(UUID channelId) void
		}
			class ConversationThread_1 {
					+UUID id
					+List~TextMessage~ messages
					+List~UserContact~ participants
					+addMessage(TextMessage message) void
					+addParticipant(UserContact participant) void
			}
		}

	class ConversationThread_2 {
	<<interfac>>
	+List~UserContact~ participants
	+UUID idd
	+List~TextMessage~ messages*
	+addParticipant(UserContact participant) void
	addMessage(TextMessage message) void
	}
							class UserContact_1 {
								+UUID id
								+String emailAddress
								+String name
								+List~CommunicationChannel~ preferredChannels
								+addCommunicationChannel(CommunicationChannel channel) void
								+removeCommunicationChannel(UUID channelId) void
								}
direction TB


	ConversationThread_1 --> UserContact
	ConversationThread_2 ..> UserContact_1


    %% Native Style Applications
    class ConversationThread:::PineSelected
    class ConversationThread_2:::ShinyStyleSelected
    class ConversationThread_1:::PineSelected

    style UserContact fill:#ce7373
    style UserContact_1 fill:#ce7373

    %% Native Style Definitions
    classDef Rose stroke-width:1px,stroke-dasharray:none,stroke:#FF5978,fill:#ad3894,color:#050505
    classDef PineSelected stroke-width:1px,stroke-dasharray:none,stroke:#275340,fill:#779c8c,color:#FFFFFF
    classDef ShinyStyleSelected fill:#a76262,stroke:#37c368



    %% @spatial:ConversationThread x=-160 y=882 w=276 h=179
    %% @spatial:ConversationThread_2 x=540 y=1243 w=328 h=227
    %% @spatial:ConversationThread_1 x=85 y=1378 w=269 h=177
    %% @spatial:UserContact x=3 y=1115 w=237 h=184
    %% @spatial:UserContact_1 x=525 y=725 w=342 h=259

    %% @style:`NewNamespace.NewNamespace2` fill=#934343
    %% @style:NewNamespace fill=#9f5b5b

    %% @note: x=-167 y=684 w=180 h=96
    note for ConversationThread "Note"
    %% @note: x=-324 y=1106 w=180 h=96
    note for ConversationThread_1 "fdsaf"
























